spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 8739
    password: 123456
    timeout: 5000
    lettuce:
      shutdown-timeout: 200
      pool:
        max-active: 500
        max-idle: 100
        min-idle: 50
        max-wait: 2000